<a href="https://colab.research.google.com/github/valuedriven/dataanalysis/blob/master/exercicio_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios NumPy

1. Faça _n_ = 200 e gere uma matriz *n X n* e dois vetores em $\mathbb{R}^n$, ambos com elementos inteiros fazendo:
    + A = np.floor(10\*rp.random.random((6,6))
    + b = np.sum(A,axis = 1)
    + z = np.ones((n,1))

In [ ]:
import numpy as np

n = 200
A = np.floor(10*np.random.random((n,n)))
b = np.sum(A,axis=1)
z = np.ones((n,1))
print(A)
print("----------------")
print(b)
print("----------------")
print(z)


a. A solução exata de Ax = b deveria ser o vetor **z**. Por que? Explique. Pode-se calcular a solução usando numpy com o método solve do pacote linalg ou calculando $A^{-1}$ e então multiplicando $A^{-1}$ por __b__. Vamos comparar os dois métodos computacionais tanto para velocidade quanto para precisão. Pode-se usar o método *time()* do pacote time para medir o tempo decorrido em cada computação. Para isso use os comandos

In [ ]:
n = 1000
A = np.floor(10*np.random.random((n,n)))
b = np.sum(A,axis = 1)
z = np.ones((n,1))

In [ ]:
A

In [ ]:
b

In [ ]:
import time
inicio = time.time()
x = np.linalg.solve(A,b)
fim = time.time()
print(fim-inicio)
inicio = time.time()
y = np.linalg.inv(A).dot(b)
fim = time.time()
print(fim-inicio)

0.002515077590942383
0.007816553115844727


Que método é mais rápido?

Para comparar a precisão dos métodos podemos medir quão próximas as soluções **x** e __y__ estão da solução exata **z**. Faça isso com os comandos

In [ ]:
print(np.max(np.abs(x-z)))
print(np.max(np.abs(y-z)))

2.6489921367556235e-13
1.4097167877480388e-11


Que método produz a soulução mais precisa?

b. Repita a parte a usando n = 500 e n = 1000.

2. Faça A = np.floor(10\*np.random.random((6,6))). Por construção a matriz A terá elementos inteiros. Vamos mudar a sexta coluna de A de modo a tornar a matriz singular. Faça

In [ ]:
A = np.floor(10*np.random.random((6,6)))
B = A.T
A[:,5] = -np.sum(B[0:5,:],axis=0)

a. Faça x = np.ones((6,1)) e calcule Ax. Como sabemos que A deve ser singular? Explique.

b. Faça B = x.dot(np.arange(1,7))
O produto AB deve ser igual à matriz nula. Por que? Explique. Verifique que isso é verdadeiro calculando AB com o método *dot*.

In [ ]:
x = np.ones((6,1))

In [ ]:
A.dot(x)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
C = np.zeros((1,6))
C[0,:] = np.arange(1,7)
C

array([[1., 2., 3., 4., 5., 6.]])

In [ ]:
B = x.dot(C)
B

array([[1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.]])

In [ ]:
A.dot(B)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])